name              'osl-matrix'
maintainer        'Oregon State University'
maintainer_email  'chef@osuosl.org'
license           'All Rights Reserved'
description       'Creates and manages a matrix synapse service for the Open Source Lab'
issues_url        'https://github.com/osuosl-cookbooks/osl-matrix/issues'
source_url        'https://github.com/osuosl-cookbooks/osl-matrix'
chef_version      '>= 16.0'
version           '0.1.0'

supports          'almalinux', '~> 8.0'

depends           'docker'
depends           'osl-docker'
depends           'osl-firewall'
depends           'osl-nginx'
depends           'osl-postgresql'
