name             'osl-matrix-test'
maintainer       'Oregon State University'
maintainer_email 'chef@osuosl.org'
license          'Apache-2.0'
description      'Test cookbook for Matrix'
version          '0.1.0'
depends          'line'
depends          'osl-matrix'
depends          'osl-postgresql'
